export const projects = [
	{
		img: 'https://github.com/RahulGaurr/Flipkart-Clone-MERN/blob/master/server/Screenshot%20(2958).png?raw=true',
		title: 'Flipkart 2.0',
		des: "An E-commerce application to sell products.",
		demo: '',
		live: "https://flipkartcloneusingmernstack.herokuapp.com/",
		gitHub: 'https://github.com/RahulGaurr/Flipkart-Clone-MERN.git',
		technologies: [ " MERN Stack || UI Liabrary: Material UI"],
	},
	{
		img: 'https://raw.githubusercontent.com/RahulGaurr/Job-Portal-Application/master/server/Screenshot%20(2961).png?token=GHSAT0AAAAAABZLDTV4RKDI7ERSPYA3VAJOYZXL5UA',
		title: 'Job Portal App',
		des: "A job portal application where you can view all jobs, apply for the job as an applicant and post jobs as a recruiter",
		demo: '',
		live: "https://jobportalmernstack.herokuapp.com/",
		gitHub: 'https://github.com/RahulGaurr/Job-Portal-Application.git',
		technologies: [ " MERN Stack || UI Liabrary: Material UI"],
	},
	{
		img: 'https://github.com/RahulGaurr/CRUD-MERN/blob/master/server/crud-admin-dashboard.png?raw=true',
		title: 'Admin Panel Dashboard',
		des: "admin panel dashboard ",
		demo: '',
		live: "https://crud-app-mern-stack.herokuapp.com/",
		gitHub: 'https://github.com/RahulGaurr/CRUD-MERN.git',
		technologies: [ " MERN Stack"],
	},
	{
		img: 'https://github.com/RahulGaurr/-My-Clotting-Store/blob/master/src/Images/my-clothing-store.png?raw=true',
		title: 'My Clothing Store',
		des: "An E-commerce application to sell wrist watches and accessories ",
		demo: '',
		live: "https://my-clothing-store-ecommerce.netlify.app/",
		gitHub: 'https://github.com/RahulGaurr/-My-Clotting-Store.git',
		technologies: [ " Technology/Library Used: React, Redux || UI Liabrary: Chakra UI"],
	},
	{
		img: 'https://github.com/RahulGaurr/fastrack.com/blob/main/Screenshot%20(1924).png?raw=true',
		title: 'Fastrack clone',
		des: "An E-commerce application to sell wrist watches and accessories.",
		demo: '',
		live: 'https://fastrack11.netlify.app/',
		gitHub: 'https://github.com/RahulGaurr/fastrack.com.git',
		technologies: [  'JavaScript',"HTML" ,'CSS'],
	},
	{
		img: 'https://github.com/RahulGaurr/interntheory.comclone/blob/main/Screenshot%20(1925).png?raw=true',
		title: 'Interntheory clone',
		des: ' A web application to sell online courses.',
		demo: '',
		live: 'https://interntheory.netlify.app/',
		gitHub: 'https://github.com/RahulGaurr/interntheory.com-clone.git',
		technologies: ['JavaScript',"HTML",'CSS', 'Node', 'Express', 'MongoDB'],
	},
	{
		img: 'https://github.com/RahulGaurr/WeatherApp/blob/main/Screenshot%20(1929).png?raw=true',
		title: 'Live Update Weather App',
		des: '  Live Weather Forcast App.',
		demo: '',
		live: 'https://weather-forecast-app-2022.netlify.app/',
		gitHub: 'https://github.com/RahulGaurr/WeatherApp.git',
		technologies: ['JavaScript',"HTML",'CSS',],
	},
	
	// {
		// 	img: 'https://camo.githubusercontent.com/b7f4aa8c34ddf776dd19b78dc3488456470a73e5026f48784e9e753601468802/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4c62507030307771454537386c6f68584d372f67697068792e676966',
		// 	title: 'Clone of Fitness Blender',
		// 	des: 'This is a clone of the Fitness Blender website. The clone is complete with a Login page, Sign-in page, Shopping Cart, Wishlist and Calendar Scheduling feature. Following is the link to the clone of the website.',
		// 	demo: '',
		// 	live: 'https://anshusagar.github.io/FitnessBlender/',
		// 	gitHub: 'https://github.com/Anshusagar/FitnessBlender.git',
		// 	technologies: ['HTML', 'CSS', 'javaScript'],
		// },
		// {
			// 	img: 'https://github.com/mandarsatam/Mailchimp-Clone/blob/master/Snips/Screenshot%20(79).png?raw=true',
			// 	title: 'Mailchimp Clone',
			// 	des: 'This is a static clone of a website called Mailchimp. This clone includes landing, pricing, our story, and the resources page.',
			// 	demo: '',
			// 	live: 'https://mandarsatam.github.io/Mailchimp-Clone/',
	// 	gitHub: 'https://github.com/mandarsatam/Mailchimp-Clone',
	// 	technologies: ['HTML', 'CSS', 'javaScript'],
	// },
	// {
	// 	img: 'https://user-images.githubusercontent.com/86410106/143928012-c66d0c3c-1f94-4894-b1f0-2326be4f3087.png',
	// 	title: 'Clone of Target.com ',
	// 	des: 'This is a clone of a US-based e-commerce website for all products built with HTML, CSS, JS. Have features that allow users to sort the product on the basis of price, on the payment page users can apply promo codes',
	// 	demo: '',
	// 	live: 'https://pandeypushpendra3.github.io/target/', // deployed link
	// 	gitHub: 'https://github.com/pandeypushpendra3/target/tree/main',
	// 	technologies: [ 'HTML', 'CSS', 'javaScript'],
	// },
];
